export const LISTINGS_GET_ALL_REQUEST = "LISTINGS_GET_ALL_REQUEST";
export const LISTINGS_GET_ALL_SUCCESS = "LISTINGS_GET_ALL_SUCCESS";
export const LISTINGS_GET_ALL_FAIL = "LISTINGS_GET_ALL_FAIL";

export const LISTING_GET_REQUEST = "LISTINGS_GET_ALL_REQUEST";
export const LISTING_GET_SUCCESS = "LISTINGS_GET_ALL_SUCCESS";
export const LISTING_GET_FAIL = "LISTINGS_GET_ALL_FAIL";

export const LISTING_POST_REQUEST = "LISTING_POST_REQUEST";
export const LISTING_POST_SUCCESS = "LISTING_POST_SUCCESS";
export const LISTING_POST_FAIL = "LISTING_POST_FAIL";

export const LISTING_UPDATE_REQUEST = "LISTING_UPDATE_REQUEST";
export const LISTING_UPDATE_SUCCESS = "LISTING_UPDATE_SUCCESS";
export const LISTING_UPDATE_FAIL = "LISTING_UPDATE_FAIL";
